/**
 * ! LINGUAGEM DA PÁGINA
 * ? Português JQUERY
 */
$(function () {
    $(".pt").click(function () {
      localStorage.setItem("language", 1);
      $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Voluntariado</a>");
      $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
      $(".h1").text("Conselho Português para os Refugiados");
      $(".description").children().eq(0).text("Ao longo de 30 anos, o CPR prestou apoio a cerca de 14,000 requerentes e refugiados em Portugal, criou respostas especializadas para as necessidades jurídicas, sociais e de integração desta população, construiu três centros de acolhimento, sendo pioneiro no ensino da Língua Portuguesa como Língua Estrangeira e Alfabetização.");
      $(".accordion").children().eq(0).text("Missão");
      $(".accordion").children().eq(2).text("Quem somos");
      $(".accordion").children().eq(4).text("Valores");
      $(".accordion").children().eq(6).text("Visão");
      $(".panel").eq(0).html("<p>Defender e promover o direito de asilo em Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>Nos termos do Direito Internacional, Europeu e Nacional dos Direitos Humanos e dos Refugiados;</li><li><i class='fa-solid fa-square squareli'></i>Através do apoio directo e gratuito, independente e imparcial, efectuado pelos vários departamentos especificamente direccionados a requerentes e beneficiários de protecção internacional com os objectivos de garantir o acesso à protecção internacional e de capacitar esta população para a integração, respectivamente;</li><li><i class='fa-solid fa-square squareli'></i>Através do acolhimento inicial e transitório de requerentes de protecção internacional e refugiados reinstalados nos Centros de Acolhimento para Refugiados, sitos na Bobadela e São João da Talha e no Centro de Acolhimento para Crianças Refugiadas;</li><li><i class='fa-solid fa-square squareli'></i>Através de advocacy junto das entidades governamentais, de forma a cumprir a visão e os valores seguidamente descritos;</li><li><i class='fa-solid fa-square squareli'></i>Através de acções de informação, sensibilização e formação, contribuindo para uma sociedade mais informada e receptiva aos refugiados.</li></ul>");
      $(".panel").eq(1).html("O CPR foi constituído em 20 de Setembro de 1991 por um conjunto de personalidades de diversos quadrantes da sociedade portuguesa. Teresa Tito de Morais foi eleita Presidente da Direção, cargo que manteve até março de 2019. É o parceiro operacional do Alto Comissariado das Nações Unidas (ACNUR) para Portugal, mantendo um Protocolo de Cooperação, desde Julho de 1993, que visa a proteção jurídica e social dos requerentes de asilo e dos refugiados. <br><br>A partir de Dezembro de 1998, data do encerramento do ACNUR em Portugal, o CPR passou a representar esta organização no nosso país.<br><br>Em 12 de Dezembro de 2000, o CPR foi distinguido com o “Prémio Direitos Humanos” da Assembleia da República. No dia 20 de Julho de 2012 foi entregue à Presidente da Direção do CPR, a Medalha de Mérito e Dedicação da Câmara Municipal de Loures. No âmbito do seu 50º aniversário, a Comissão Episcopal da Pastoral Social e Mobilidade Humana, numa cerimónia realizada na Fundação Calouste Gulbenkian, em dezembro de 2012, homenageou o CPR “pelo excelente trabalho que desenvolve no apoio aos refugiados e por ser uma instituição parceira de referência para a Obra Católica Portuguesa para as Migrações”.");
      $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Os Direitos Humanos;</li><li><i class='fa-solid fa-square squareli'></i>Inclusão e empoderamento dos requerentes e beneficiários de protecção internacional;</li><li><i class='fa-solid fa-square squareli'></i>Sociedade inclusiva e consciente das suas responsabilidades nos domínios do asilo;</li><li><i class='fa-solid fa-square squareli'></i>Transparência, independência, rigor e integridade;</li><li><i class='fa-solid fa-square squareli'></i>Espírito de equipa, trabalho em parceria e em rede (local e comunitária), formas essenciais de cooperação e colaboração para concretizar os objectivos.</li></ul>");
      $(".panel").eq(3).html("Que Portugal cumpra os compromissos internacionalmente assumidos e a legislação relativa a direitos humanos e ao direito de asilo e tenha uma cooperação internacional, assuma responsabilidade acrescida no sistema internacional e europeu de protecção, nomeadamente no âmbito da Reinstalação e de mecanismos de solidariedade. <br><br>Respeite a dignidade dos requerentes de protecção internacional, assegurando a quem seja reconhecida protecção, a possibilidade de se integrar e desenvolver. O CPR é, e continuará a ser, a organização de referência em termos da defesa e promoção do direito de asilo em Portugal.");
    });
  });
  /**
   * ! LINGUAGEM DA PÁGINA
   * ? Inglês JQUERY
   */
  $(function () {
    $(".en").click(function () {
      localStorage.setItem("language", 2);
          $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Volunteer</a>");
          $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
          $(".h1").text("Conselho Português para os Refugiados");
          $(".description").children().eq(0).text("Over 30 years, the CPR has provided support to around 14,000 applicants and refugees in Portugal, created specialized responses to the legal, social and integration needs of this population, built three reception centres, being a pioneer in teaching Portuguese as a language Foreign and Literacy.");
          $(".accordion").children().eq(0).text("Mission");
          $(".accordion").children().eq(2).text("About us");
          $(".accordion").children().eq(4).text("Valores");
          $(".accordion").children().eq(6).text("Eyesight");
          $(".panel").eq(0).html("<p>Defend and promote the right to asylum in Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>Under the terms of International, European and National Law on Human and Refugee Rights;</li><li><i class='fa-solid fa-square squareli'></i>Through the direct and free, independent and impartial support carried out by the various departments specifically aimed at applicants and beneficiaries of international protection with the objectives of guaranteeing access to international protection and enabling this population to integrate, respectively;</li><li><i class='fa-solid fa-square squareli'></i>Through the initial and transitional reception of applicants for international protection and resettled refugees in the Reception Centers for Refugees, located in Bobadela and São João da Talha and in the Reception Center for Refugee Children;</li><li><i class='fa-solid fa-square squareli'></i>Through advocacy with government entities, in order to fulfill the vision and values described below;</li><li><i class='fa-solid fa-square squareli'></i>Through information, awareness and training actions, contributing to a society that is more informed and receptive to refugees.</li></ul>");
          $(".panel").eq(1).html("The CPR was formed on September 20, 1991 by a group of personalities from different quarters of Portuguese society. Teresa Tito de Morais was elected President of the Board, a position she held until March 2019. She is the operational partner of the United Nations High Commissioner (UNHCR) for Portugal, maintaining a Cooperation Protocol, since July 1993, which aims at legal protection and social life of asylum seekers and refugees. <br><br>From December 1998, date of closure of UNHCR in Portugal, the CPR started to represent this organization in our country.<br><br>On December 12, 2000, the CPR was distinguished with the “Human Rights Award” of the Assembly of the Republic. On the 20th of July 2012, the President of the Board of the CPR was awarded the Medal of Merit and Dedication by the Municipality of Loures. As part of its 50th anniversary, the Episcopal Commission for Social Pastoral and Human Mobility, in a ceremony held at the Calouste Gulbenkian Foundation in December 2012, honored the CPR “for the excellent work it does in supporting refugees and for being a partner institution of reference for the Portuguese Catholic Work for Migrations”.");
          $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Human Rights;</li><li><i class='fa-solid fa-square squareli'></i>Inclusion and empowerment of applicants and beneficiaries of international protection;</li><li><i class='fa-solid fa-square squareli'></i>An inclusive society aware of its responsibilities in the areas of asylum;</li><li><i class='fa-solid fa-square squareli'></i>Transparency, independence, rigor and integrity;</li><li><i class='fa-solid fa-square squareli'></i>Team spirit, working in partnership and networking (local and community), essential forms of cooperation and collaboration to achieve the objectives.</li></ul>");
          $(".panel").eq(3).html("That Portugal fulfills the internationally assumed commitments and the legislation related to human rights and the right of asylum and has international cooperation, assumes increased responsibility in the international and European system of protection, namely in the scope of Resettlement and solidarity mechanisms. <br><br>Respect the dignity of applicants for international protection, ensuring that those who are recognized for protection have the opportunity to integrate and develop. The CPR is, and will continue to be, the reference organization in terms of the defense and promotion of the right to asylum in Portugal.");
        });
  });
  /**
   * ! LINGUAGEM DA PÁGINA
   * ? Françes JQUERY
   */
  $(function () {
    $(".fr").click(function () {
      localStorage.setItem("language", 3);
      $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Volunteer</a>");
      $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
      $(".h1").text("Conselho Português para os Refugiados");
      $(".description").children().eq(0).text("En 30 ans, le CPR a soutenu environ 14 000 demandeurs et réfugiés au Portugal, créé des réponses spécialisées aux besoins juridiques, sociaux et d'intégration de cette population, construit trois centres d'accueil, étant un pionnier dans l'enseignement du portugais comme langue étrangère et alphabétisation.");
      $(".accordion").children().eq(0).text("Mission");
      $(".accordion").children().eq(2).text("À propos de nous");
      $(".accordion").children().eq(4).text("Valeurs");
      $(".accordion").children().eq(6).text("Vue");
      $(".panel").eq(0).html("<p>Défendre et promouvoir le droit d'asile au Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>En vertu des lois internationales, européennes et nationales sur les droits de l'homme et des réfugiés;</li><li><i class='fa-solid fa-square squareli'></i>Par l'accompagnement direct et gratuit, indépendant et impartial effectué par les différents services spécifiquement destinés aux demandeurs et bénéficiaires de protection internationale dans le but de garantir l'accès à la protection internationale et de permettre à cette population de s'intégrer, respectivement;</li><li><i class='fa-solid fa-square squareli'></i>Par l'accueil initial et transitoire des demandeurs de protection internationale et des réfugiés réinstallés dans les centres d'accueil pour réfugiés, situés à Bobadela et São João da Talha et dans le centre d'accueil pour enfants réfugiés;</li><li><i class='fa-solid fa-square squareli'></i>Grâce au plaidoyer auprès des entités gouvernementales, afin de réaliser la vision et les valeurs décrites ci-dessous;</li><li><i class='fa-solid fa-square squareli'></i>Par des actions d'information, de sensibilisation et de formation, contribuer à une société plus informée et réceptive aux réfugiés.</li></ul>");
      $(".panel").eq(1).html("Le CPR a été formé le 20 septembre 1991 par un groupe de personnalités issues de différents milieux de la société portugaise. Teresa Tito de Morais a été élue présidente du conseil d'administration, poste qu'elle a occupé jusqu'en mars 2019. Elle est le partenaire opérationnel du Haut-Commissariat des Nations Unies (HCR) pour le Portugal, maintenant un protocole de coopération, depuis juillet 1993, qui vise à la protection juridique et la vie sociale des demandeurs d'asile et des réfugiés. <br><br>A partir de décembre 1998, date de la fermeture du HCR au Portugal, le CPR a commencé à représenter cette organisation dans notre pays.<br><br>Le 12 décembre 2000, le CPR a été distingué par le « Human Rights Prix » de l'Assemblée de la République. Le 20 juillet 2012, le Président du Conseil d'Administration du CPR a reçu la Médaille du Mérite et du Dévouement par la Municipalité de Loures. Dans le cadre de son 50e anniversaire, la Commission épiscopale de pastorale sociale et de mobilité humaine, lors d'une cérémonie tenue à la Fondation Calouste Gulbenkian en décembre 2012, a honoré le CPR « pour l'excellent travail qu'il accomplit dans l'accompagnement des réfugiés et pour être une institution partenaire de référence pour l'Œuvre Catholique Portugaise pour les Migrations ».");
      $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Droits humains;</li><li><i class='fa-solid fa-square squareli'></i>Inclusion et autonomisation des demandeurs et bénéficiaires de protection internationale;</li><li><i class='fa-solid fa-square squareli'></i>Une société inclusive consciente de ses responsabilités en matière d'asile;</li><li><i class='fa-solid fa-square squareli'></i>Transparence, indépendance, rigueur et intégrité;</li><li><i class='fa-solid fa-square squareli'></i>Esprit d'équipe, travail en partenariat et en réseau (local et communautaire), formes essentielles de coopération et de collaboration pour atteindre les objectifs.</li></ul>");
      $(".panel").eq(3).html("Que le Portugal respecte les engagements pris au niveau international et la législation relative aux droits de l'homme et au droit d'asile et dispose d'une coopération internationale, assume une responsabilité accrue dans le système international et européen de protection, notamment dans le cadre des mécanismes de réinstallation et de solidarité. <br><br>Respecter la dignité des demandeurs de protection internationale, en veillant à ce que ceux dont la protection est reconnue aient la possibilité de s'intégrer et de se développer. Le CPR est et restera l'organisation de référence en matière de défense et de promotion du droit d'asile au Portugal.");
    });
  });

  
addEventListener("DOMContentLoaded", (event) => {
  if (localStorage.getItem("language") == 1) {
    $(function () {
      localStorage.setItem("language", 1);
      $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Voluntariado</a>");
      $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
      $(".h1").text("Conselho Português para os Refugiados");
      $(".description").children().eq(0).text("Ao longo de 30 anos, o CPR prestou apoio a cerca de 14,000 requerentes e refugiados em Portugal, criou respostas especializadas para as necessidades jurídicas, sociais e de integração desta população, construiu três centros de acolhimento, sendo pioneiro no ensino da Língua Portuguesa como Língua Estrangeira e Alfabetização.");
      $(".accordion").children().eq(0).text("Missão");
      $(".accordion").children().eq(2).text("Quem somos");
      $(".accordion").children().eq(4).text("Valores");
      $(".accordion").children().eq(6).text("Visão");
      $(".panel").eq(0).html("<p>Defender e promover o direito de asilo em Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>Nos termos do Direito Internacional, Europeu e Nacional dos Direitos Humanos e dos Refugiados;</li><li><i class='fa-solid fa-square squareli'></i>Através do apoio directo e gratuito, independente e imparcial, efectuado pelos vários departamentos especificamente direccionados a requerentes e beneficiários de protecção internacional com os objectivos de garantir o acesso à protecção internacional e de capacitar esta população para a integração, respectivamente;</li><li><i class='fa-solid fa-square squareli'></i>Através do acolhimento inicial e transitório de requerentes de protecção internacional e refugiados reinstalados nos Centros de Acolhimento para Refugiados, sitos na Bobadela e São João da Talha e no Centro de Acolhimento para Crianças Refugiadas;</li><li><i class='fa-solid fa-square squareli'></i>Através de advocacy junto das entidades governamentais, de forma a cumprir a visão e os valores seguidamente descritos;</li><li><i class='fa-solid fa-square squareli'></i>Através de acções de informação, sensibilização e formação, contribuindo para uma sociedade mais informada e receptiva aos refugiados.</li></ul>");
      $(".panel").eq(1).html("O CPR foi constituído em 20 de Setembro de 1991 por um conjunto de personalidades de diversos quadrantes da sociedade portuguesa. Teresa Tito de Morais foi eleita Presidente da Direção, cargo que manteve até março de 2019. É o parceiro operacional do Alto Comissariado das Nações Unidas (ACNUR) para Portugal, mantendo um Protocolo de Cooperação, desde Julho de 1993, que visa a proteção jurídica e social dos requerentes de asilo e dos refugiados. <br><br>A partir de Dezembro de 1998, data do encerramento do ACNUR em Portugal, o CPR passou a representar esta organização no nosso país.<br><br>Em 12 de Dezembro de 2000, o CPR foi distinguido com o “Prémio Direitos Humanos” da Assembleia da República. No dia 20 de Julho de 2012 foi entregue à Presidente da Direção do CPR, a Medalha de Mérito e Dedicação da Câmara Municipal de Loures. No âmbito do seu 50º aniversário, a Comissão Episcopal da Pastoral Social e Mobilidade Humana, numa cerimónia realizada na Fundação Calouste Gulbenkian, em dezembro de 2012, homenageou o CPR “pelo excelente trabalho que desenvolve no apoio aos refugiados e por ser uma instituição parceira de referência para a Obra Católica Portuguesa para as Migrações”.");
      $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Os Direitos Humanos;</li><li><i class='fa-solid fa-square squareli'></i>Inclusão e empoderamento dos requerentes e beneficiários de protecção internacional;</li><li><i class='fa-solid fa-square squareli'></i>Sociedade inclusiva e consciente das suas responsabilidades nos domínios do asilo;</li><li><i class='fa-solid fa-square squareli'></i>Transparência, independência, rigor e integridade;</li><li><i class='fa-solid fa-square squareli'></i>Espírito de equipa, trabalho em parceria e em rede (local e comunitária), formas essenciais de cooperação e colaboração para concretizar os objectivos.</li></ul>");
      $(".panel").eq(3).html("Que Portugal cumpra os compromissos internacionalmente assumidos e a legislação relativa a direitos humanos e ao direito de asilo e tenha uma cooperação internacional, assuma responsabilidade acrescida no sistema internacional e europeu de protecção, nomeadamente no âmbito da Reinstalação e de mecanismos de solidariedade. <br><br>Respeite a dignidade dos requerentes de protecção internacional, assegurando a quem seja reconhecida protecção, a possibilidade de se integrar e desenvolver. O CPR é, e continuará a ser, a organização de referência em termos da defesa e promoção do direito de asilo em Portugal.");
    });
  } else if (localStorage.getItem("language") == 2) {
    $(function () {
      localStorage.setItem("language", 2);
      $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Volunteer</a>");
          $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
          $(".h1").text("Conselho Português para os Refugiados");
          $(".description").children().eq(0).text("Over 30 years, the CPR has provided support to around 14,000 applicants and refugees in Portugal, created specialized responses to the legal, social and integration needs of this population, built three reception centres, being a pioneer in teaching Portuguese as a language Foreign and Literacy.");
          $(".accordion").children().eq(0).text("Mission");
          $(".accordion").children().eq(2).text("About us");
          $(".accordion").children().eq(4).text("Values");
          $(".accordion").children().eq(6).text("Eyesight");
          $(".panel").eq(0).html("<p>Defend and promote the right to asylum in Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>Under the terms of International, European and National Law on Human and Refugee Rights;</li><li><i class='fa-solid fa-square squareli'></i>Through the direct and free, independent and impartial support carried out by the various departments specifically aimed at applicants and beneficiaries of international protection with the objectives of guaranteeing access to international protection and enabling this population to integrate, respectively;</li><li><i class='fa-solid fa-square squareli'></i>Through the initial and transitional reception of applicants for international protection and resettled refugees in the Reception Centers for Refugees, located in Bobadela and São João da Talha and in the Reception Center for Refugee Children;</li><li><i class='fa-solid fa-square squareli'></i>Through advocacy with government entities, in order to fulfill the vision and values described below;</li><li><i class='fa-solid fa-square squareli'></i>Through information, awareness and training actions, contributing to a society that is more informed and receptive to refugees.</li></ul>");
          $(".panel").eq(1).html("The CPR was formed on September 20, 1991 by a group of personalities from different quarters of Portuguese society. Teresa Tito de Morais was elected President of the Board, a position she held until March 2019. She is the operational partner of the United Nations High Commissioner (UNHCR) for Portugal, maintaining a Cooperation Protocol, since July 1993, which aims at legal protection and social life of asylum seekers and refugees. <br><br>From December 1998, date of closure of UNHCR in Portugal, the CPR started to represent this organization in our country.<br><br>On December 12, 2000, the CPR was distinguished with the “Human Rights Award” of the Assembly of the Republic. On the 20th of July 2012, the President of the Board of the CPR was awarded the Medal of Merit and Dedication by the Municipality of Loures. As part of its 50th anniversary, the Episcopal Commission for Social Pastoral and Human Mobility, in a ceremony held at the Calouste Gulbenkian Foundation in December 2012, honored the CPR “for the excellent work it does in supporting refugees and for being a partner institution of reference for the Portuguese Catholic Work for Migrations”.");
          $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Human Rights;</li><li><i class='fa-solid fa-square squareli'></i>Inclusion and empowerment of applicants and beneficiaries of international protection;</li><li><i class='fa-solid fa-square squareli'></i>An inclusive society aware of its responsibilities in the areas of asylum;</li><li><i class='fa-solid fa-square squareli'></i>Transparency, independence, rigor and integrity;</li><li><i class='fa-solid fa-square squareli'></i>Team spirit, working in partnership and networking (local and community), essential forms of cooperation and collaboration to achieve the objectives.</li></ul>");
          $(".panel").eq(3).html("That Portugal fulfills the internationally assumed commitments and the legislation related to human rights and the right of asylum and has international cooperation, assumes increased responsibility in the international and European system of protection, namely in the scope of Resettlement and solidarity mechanisms. <br><br>Respect the dignity of applicants for international protection, ensuring that those who are recognized for protection have the opportunity to integrate and develop. The CPR is, and will continue to be, the reference organization in terms of the defense and promotion of the right to asylum in Portugal.");
    });
  } else if (localStorage.getItem("language") == 3) {
    $(function () {
      localStorage.setItem("language", 3);
      $(".breadcrumb-item").eq(0).html("<a href='http://localhost/STR/voluntariado/voluntariado.php'>Faire du Bénévole</a>");
          $(".breadcrumb-item").eq(1).text("Conselho Português para os Refugiados");
          $(".h1").text("Conselho Português para os Refugiados");
          $(".description").children().eq(0).text("En 30 ans, le CPR a soutenu environ 14 000 demandeurs et réfugiés au Portugal, créé des réponses spécialisées aux besoins juridiques, sociaux et d'intégration de cette population, construit trois centres d'accueil, étant un pionnier dans l'enseignement du portugais comme langue étrangère et alphabétisation.");
          $(".accordion").children().eq(0).text("Mission");
          $(".accordion").children().eq(2).text("À propos de nous");
          $(".accordion").children().eq(4).text("Valeurs");
          $(".accordion").children().eq(6).text("Vue");
          $(".panel").eq(0).html("<p>Défendre et promouvoir le droit d'asile au Portugal</p><ul><li><i class='fa-solid fa-square squareli'></i>En vertu des lois internationales, européennes et nationales sur les droits de l'homme et des réfugiés;</li><li><i class='fa-solid fa-square squareli'></i>Par l'accompagnement direct et gratuit, indépendant et impartial effectué par les différents services spécifiquement destinés aux demandeurs et bénéficiaires de protection internationale dans le but de garantir l'accès à la protection internationale et de permettre à cette population de s'intégrer, respectivement;</li><li><i class='fa-solid fa-square squareli'></i>Par l'accueil initial et transitoire des demandeurs de protection internationale et des réfugiés réinstallés dans les centres d'accueil pour réfugiés, situés à Bobadela et São João da Talha et dans le centre d'accueil pour enfants réfugiés;</li><li><i class='fa-solid fa-square squareli'></i>Grâce au plaidoyer auprès des entités gouvernementales, afin de réaliser la vision et les valeurs décrites ci-dessous;</li><li><i class='fa-solid fa-square squareli'></i>Par des actions d'information, de sensibilisation et de formation, contribuer à une société plus informée et réceptive aux réfugiés.</li></ul>");
          $(".panel").eq(1).html("Le CPR a été formé le 20 septembre 1991 par un groupe de personnalités issues de différents milieux de la société portugaise. Teresa Tito de Morais a été élue présidente du conseil d'administration, poste qu'elle a occupé jusqu'en mars 2019. Elle est le partenaire opérationnel du Haut-Commissariat des Nations Unies (HCR) pour le Portugal, maintenant un protocole de coopération, depuis juillet 1993, qui vise à la protection juridique et la vie sociale des demandeurs d'asile et des réfugiés. <br><br>A partir de décembre 1998, date de la fermeture du HCR au Portugal, le CPR a commencé à représenter cette organisation dans notre pays.<br><br>Le 12 décembre 2000, le CPR a été distingué par le « Human Rights Prix » de l'Assemblée de la République. Le 20 juillet 2012, le Président du Conseil d'Administration du CPR a reçu la Médaille du Mérite et du Dévouement par la Municipalité de Loures. Dans le cadre de son 50e anniversaire, la Commission épiscopale de pastorale sociale et de mobilité humaine, lors d'une cérémonie tenue à la Fondation Calouste Gulbenkian en décembre 2012, a honoré le CPR « pour l'excellent travail qu'il accomplit dans l'accompagnement des réfugiés et pour être une institution partenaire de référence pour l'Œuvre Catholique Portugaise pour les Migrations ».");
          $(".panel").eq(2).html("<ul><li><i class='fa-solid fa-square squareli'></i>Droits humains;</li><li><i class='fa-solid fa-square squareli'></i>Inclusion et autonomisation des demandeurs et bénéficiaires de protection internationale;</li><li><i class='fa-solid fa-square squareli'></i>Une société inclusive consciente de ses responsabilités en matière d'asile;</li><li><i class='fa-solid fa-square squareli'></i>Transparence, indépendance, rigueur et intégrité;</li><li><i class='fa-solid fa-square squareli'></i>Esprit d'équipe, travail en partenariat et en réseau (local et communautaire), formes essentielles de coopération et de collaboration pour atteindre les objectifs.</li></ul>");
          $(".panel").eq(3).html("Que le Portugal respecte les engagements pris au niveau international et la législation relative aux droits de l'homme et au droit d'asile et dispose d'une coopération internationale, assume une responsabilité accrue dans le système international et européen de protection, notamment dans le cadre des mécanismes de réinstallation et de solidarité. <br><br>Respecter la dignité des demandeurs de protection internationale, en veillant à ce que ceux dont la protection est reconnue aient la possibilité de s'intégrer et de se développer. Le CPR est et restera l'organisation de référence en matière de défense et de promotion du droit d'asile au Portugal.");
    });
  }
});

$(document).ready(function() {
  $(document).on('click', '#btn_more', function() {
      var last_video_id = $(this).data("vid");
      var language = localStorage.getItem("language");
      $.ajax({
          url: "load_data.php",
          method: "POST",
          data: {
              last_video_id: last_video_id,
              language: language,
              db: "comentarios_cpr"
          },
          dataType: "text",
          success: function(data) {
              if (data != '') {
                  $('#remove_row').remove();
                  $('#load_data_table').append(data);
              } else {

              }
          }
      });
  });
});